# -----------------------
# -----    Model    -----
# -----------------------
model:
    n_blocks: 5
    filter_factors: null
    kernel_size: 3
    dropout: 0.25
    Cin: 44
    Cout: 3
    Cnoise: 0
# ------------------------------
# -----    Train Params    -----
# ------------------------------
train:
    batch_size: 32
    early_break_epoch: 0
    infer_every_steps: 5000
    lambda_gan: 0.01
    lambda_L: 1
    load_limit: -1
    lr_d: 0.0002
    lr_g: 0.00005
    matching_loss: "l2"
    n_epochs: 100
    num_D_accumulations: 8
    save_every_steps: 5000
    store_images: false
# ---------------------------
# -----    Data Conf    -----
# ---------------------------
data:
    path: "/scratch/sankarak/data/clouds/"
    n_in_mem: 1
    num_workers: 3
    with_stats: true
